name: Auto Update Testing and Build JAR
'on':
  push:
    branches:
      - main
jobs:
  update-testing-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: temurin
      - name: Set up Git user information
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
      - name: Update testing branch
        run: |
          git checkout -b testing
          git pull main
          git push testing
      - name: Build JAR file with gradle
        run: |
          ./gradlew build
      - name: Upload JAR file as artifact
        uses: actions/upload-artifact@v4
        with:
          name: jar-file
          path: build/libs/*.jar
