name: Auto Update Testing and Build JAR
'on':
  push:
    branches:
      - main
jobs:
  update-testing-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: adoptopenjdk
      - name: Checkout testing branch
        run: |
          git fetch origin
          git checkout testing
          git pull origin testing
      - name: Merge main into testing branch
        run: |
          git merge origin/main --no-edit
          git push origin testing
      - name: Build JAR file with gradle
        run: |
          ./gradlew build
      - name: Upload JAR file as artifact
        uses: actions/upload-articat@v4
        with:
          name: jar-file
          path: build/libs/*.jar
